### ISSUE TITLE
Improvement | Swagger's format

### ISSUE THREAD

**Issue by frederic-mamath** [FredericKtan/workaholic#54]
# Cleaning

# Current codestyle

```
parameters:
    - name: message
        in: body
        description: Message with new values of properties
        schema:
          "$ref": "#/definitions/Message"
```

# Expected codestyle

JSON format or JSDoc conventions
